export default {
    HOME:"INICIO",
    LOGIN:"INICIAR SESIÓN",
    SIGNUP:"REGISTRO",
    TABS:"Bienvenido",
    HOMEVIEW:"Licy",
    ADMINISTRACION:"ADMINISTRACIÓN",
    LICITACIONES:"LICITACIONES",
    CONFIGURACION:"CONFIGURACIÓN",
    DASHBOARD:"DASHBOARD",
    FAVORITOS:"MIS FAVORITOS",
    HISTORICO:"HISTÓRICO",
    MISEMPRESAS:"MIS EMPRESAS",
    MISLICITACIONES:"MIS LICITACIONES",
    NUEVASLICITACIONES:"NUEVAS LICITACIONES",
    PAGOS:"PAGOS",
    PREFERENCIAS:"MIS PREFERENCIAS",
    COLABORADORES:"MIS COLABORADORES",
    MICUENTA:"MI CUENTA",
    FLUJOSANEXOS :"FLUJOS ANEXOS",
    FLUJOS:"FLUJOS",
    APP:"BIENVENIDO A LICY"







}